name: Build

on:
  pull_request:
    branches: [main]
    paths: ["**/*.bicep"]

jobs:
  bicep-build:
    name: Bicep Build
    runs-on: ubuntu-latest
    env:
      BICEP_FILE_PATH: main.bicep
      OUTPUT_FILE_PATH: azuredeploy.json
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.head_ref }} # Required to push commit to PR

      - name: Build Bicep file
        run: az bicep build --file "$BICEP_FILE_PATH" --outfile "$OUTPUT_FILE_PATH"

      - name: Push commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUTPUT_FILE_PATH"
          git commit -m "Build Bicep file"
          git push
